apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config-toml
data:
  config.toml: |
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        [[runners.kubernetes.volumes.secret]]
          name = "gitlab-ca-certs"
          mount_path = "/home/gitlab-runner/.gitlab-runner/certs"
          [runners.kubernetes.volumes.secret.items]
            "hostname.crt" = "gitlab.developer.hkn.lab.crt"
