kind: ConfigMap
apiVersion: v1
metadata:
  name: gitlab-runner-config-toml
  namespace: gitlab-runner
data:
  config.toml: |
    [[runners]]
      [runners.kubernetes]
        [[runners.kubernetes.volumes.pvc]]
          name = "varlibcontainers"
          mount_path = "/var/lib/containers"

