apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2021-03-16T18:26:01Z"
  generation: 1
  managedFields:
  - apiVersion: operators.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
    manager: cluster-version-operator
    operation: Update
    time: "2021-03-16T18:26:01Z"
  - apiVersion: operators.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec: {}
      f:status:
        .: {}
        f:lastUpdated: {}
        f:namespaces:
          .: {}
          v:"": {}
    manager: olm
    operation: Update
    time: "2021-03-16T18:37:47Z"
  name: global-operators
  namespace: openshift-operators
  resourceVersion: "9100"
  selfLink: /apis/operators.coreos.com/v1/namespaces/openshift-operators/operatorgroups/global-operators
  uid: 51b59b89-20e1-4a89-b5e1-376864b2daee
status:
  lastUpdated: "2021-03-16T18:37:47Z"
  namespaces:
  - ""
