apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-runner-operator
  namespace: gitlab-runners
spec:
  channel: beta
  name: gitlab-runner-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gitlab-runner-operator.v13.8.0
